export type Category =
  | 'clay-pendants'
  | 'clay-earrings'
  | 'handmade-jewellery'
  | 'oxidised-earrings'

export interface Product {
  id: string
  name: string
  tagline: string
  description: string
  price: number
  originalPrice?: number
  image: string
  category: Category
  badge?: 'New' | 'Bestseller'
  /** Empty array = no variant picker shown */
  variants: string[]
  materials: string
  dimensions: string
  care: string
  leadTime: string
  isActive: boolean
}

export const CATEGORIES: { value: Category; label: string }[] = [
  { value: 'clay-pendants', label: 'Clay Pendants' },
  { value: 'clay-earrings', label: 'Clay Earrings' },
  { value: 'handmade-jewellery', label: 'Handmade Jewellery' },
  { value: 'oxidised-earrings', label: 'Oxidised Earrings' },
]

export const products: Product[] = [
  // Clay Pendants & Sets
  {
    id: 'clay-set-01',
    name: 'Terracotta Blossom Clay Set',
    tagline: 'Hand-sculpted clay pendant with matching earrings',
    description: 'Each bead and pendant is hand-rolled and painted individually from fine clay, finished with a protective natural seal. Lightweight and hypoallergenic.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-01.jpg',
    category: 'clay-pendants',
    badge: 'New',
    variants: [],
    materials: 'Air-dry natural clay, non-toxic pigment, cotton dori cord',
    dimensions: 'Pendant: ~5cm, Earring drop: ~3.5cm',
    care: 'Avoid direct contact with water, perfume, and harsh chemicals. Store in an airtight pouch.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-set-02',
    name: 'Earth & Petal Clay Set',
    tagline: 'Warm terracotta tones with intricate handcrafted motifs',
    description: 'Designed with botanical inspirations from Bengal nature. Each set comes with a sculpted centerpiece pendant and matching earrings.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-02.jpg',
    category: 'clay-pendants',
    variants: [],
    materials: 'Hand-sculpted clay, artisan acrylics, silk thread cord',
    dimensions: 'Pendant: ~4.5cm, Cord: adjustable',
    care: 'Wipe gently with a soft dry cloth. Keep away from excessive moisture.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-pendant-03',
    name: 'Floral Mandala Clay Pendant',
    tagline: 'Intricate hand-painted mandala artwork on sculpted clay',
    description: 'Features vibrant festive hues drawn from traditional Bengali alpana and floral folklore on a centerpiece clay pendant.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-03.jpg',
    category: 'clay-pendants',
    badge: 'Bestseller',
    variants: [],
    materials: 'Natural clay, hand-painted acrylics, cotton cord',
    dimensions: 'Pendant: ~5cm diameter, Cord: adjustable',
    care: 'Gently wipe clean with dry microfiber cloth. Do not submerge in water.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-set-05',
    name: 'Rustic Bloom Clay Pendant Set',
    tagline: 'Hand-moulded organic clay jewellery with earthy tones',
    description: 'Rich earthy textures shaped with unhurried care. An ode to slow craft and mindful artisan jewellery making.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-05.jpg',
    category: 'clay-pendants',
    badge: 'New',
    variants: [],
    materials: 'Natural clay, mineral pigments, soft fabric cord',
    dimensions: 'Pendant: ~5.5cm, Earrings: ~4cm',
    care: 'Store in dry place. Clean with dry cloth only.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },

  // Clay Earrings
  {
    id: 'clay-earring-01',
    name: 'Terracotta Blossom Drop Earrings',
    tagline: 'Featherlight sculpted clay drops with floral hand-painting',
    description: 'Meticulously crafted from kiln-cured terracotta clay. Designed for lightweight comfort and subtle festive elegance.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-01.jpg',
    category: 'clay-earrings',
    badge: 'New',
    variants: [],
    materials: 'Natural clay, hypoallergenic hooks, non-toxic pigment',
    dimensions: 'Drop length: ~3.5cm',
    care: 'Keep away from moisture and perfume.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-earring-02',
    name: 'Earth & Petal Terracotta Earrings',
    tagline: 'Organic botanic motifs hand-sculpted on natural clay',
    description: 'Warm earthy hues inspired by Bengal pottery traditions, finished with a smooth satin sheen.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-02.jpg',
    category: 'clay-earrings',
    variants: [],
    materials: 'Clay, artisan acrylics, brass hooks',
    dimensions: 'Earring drop: ~3.8cm',
    care: 'Wipe with soft cloth. Store in pouch.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-set-03',
    name: 'Floral Mandala Clay Earrings',
    tagline: 'Detailed hand-painted mandala artwork on sculpted clay',
    description: 'Features vibrant festive hues drawn from traditional Bengali alpana and floral folklore. Perfectly paired for festive celebrations.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-03.jpg',
    category: 'clay-earrings',
    badge: 'Bestseller',
    variants: [],
    materials: 'Natural clay, hand-painted acrylics, brass ear hooks',
    dimensions: 'Earrings: ~4cm drop',
    care: 'Gently wipe clean. Do not submerge in water.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },
  {
    id: 'clay-set-04',
    name: 'Sonartari Hand-painted Clay Earrings',
    tagline: 'Golden accented clay motifs inspired by Bengal heritage',
    description: 'A harmonious blend of earthy clay texture and delicate hand-painted accents with lightweight brass hooks.',
    price: 159,
    image: '/images/products/clay-jewellery/clay-04.jpg',
    category: 'clay-earrings',
    variants: [],
    materials: 'Crafted clay, golden highlights, brass hooks',
    dimensions: 'Earrings: ~3.5cm',
    care: 'Store separately in a cotton bag away from direct sunlight.',
    leadTime: 'Made to order. Dispatched in 3–5 working days.',
    isActive: true,
  },

  // Handmade Jewellery Sets
  {
    id: 'handmade-set-01',
    name: 'Classic Crafted Choker & Earring Set',
    tagline: 'Traditional handcrafted choker with delicate coordinating earrings',
    description: 'A statement handcrafted piece combining traditional craftsmanship with contemporary elegance. Perfect for weddings, festivals, and cultural events.',
    price: 180,
    image: '/images/products/handmade-jewellery/handmade-01.jpg',
    category: 'handmade-jewellery',
    badge: 'Bestseller',
    variants: [],
    materials: 'Mixed craft metal, glass beads, artisanal cotton cord',
    dimensions: 'Choker length: ~22cm + adjustable cord',
    care: 'Keep in zip-lock pouch after each wear. Avoid water contact.',
    leadTime: 'Dispatched within 2–4 working days.',
    isActive: true,
  },
  {
    id: 'handmade-set-02',
    name: 'Traditional Handcrafted Neckpiece Set',
    tagline: 'Artisanal neckpiece with intricate detailing and matching earrings',
    description: 'Designed and crafted one piece at a time. Rich textural detail that adds a dignified festive charm to ethnic and fusion attire.',
    price: 200,
    image: '/images/products/handmade-jewellery/handmade-02.jpg',
    category: 'handmade-jewellery',
    variants: [],
    materials: 'Brass alloy, beads, handcrafted thread work',
    dimensions: 'Neckpiece drop: ~8cm, Earrings: ~4.5cm',
    care: 'Store in an airtight container with silica gel.',
    leadTime: 'Dispatched within 2–4 working days.',
    isActive: true,
  },
  {
    id: 'handmade-set-03',
    name: 'Festive Heritage Jewellery Set',
    tagline: 'Exquisite layered handcrafted festive jewellery set',
    description: 'Crafted for celebratory moments, this set features detailed handcrafted elements that celebrate the grandeur of Indian craftsmanship.',
    price: 260,
    image: '/images/products/handmade-jewellery/handmade-03.jpg',
    category: 'handmade-jewellery',
    badge: 'New',
    variants: [],
    materials: 'Silver-look alloy, ghungroo beads, handcrafted cord',
    dimensions: 'Full necklace length: ~28cm, Earrings: ~5cm',
    care: 'Keep away from moisture, hairsprays, and perfumes.',
    leadTime: 'Dispatched within 3–5 working days.',
    isActive: true,
  },
  {
    id: 'handmade-set-04',
    name: 'Ornate Hand-strung Jewellery Set',
    tagline: 'Statement artisanal neckpiece with sculpted motifs',
    description: 'Intricately assembled with precision and care, creating a distinctive piece that anchors any celebratory look.',
    price: 260,
    image: '/images/products/handmade-jewellery/handmade-04.jpg',
    category: 'handmade-jewellery',
    variants: [],
    materials: 'Oxidised metal, artisanal cords, ornamental beads',
    dimensions: 'Necklace: ~26cm + adjustable cord, Earrings: ~5.5cm',
    care: 'Wipe with microfiber cloth. Store flat in soft cloth pouch.',
    leadTime: 'Dispatched within 3–5 working days.',
    isActive: true,
  },

  // Oxidised Earrings
  {
    id: 'oxidised-01',
    name: 'Delicate Floral Oxidised Jhumkis',
    tagline: 'Classic floral studs with lightweight hanging jhumka dome',
    description: 'Timeless oxidised silver-finish earrings featuring delicate floral engraving and tiny chime ghungroos. Feather-light for day-long wear.',
    price: 99,
    image: '/images/products/oxidised-earrings/oxidised-01.jpg',
    category: 'oxidised-earrings',
    badge: 'Bestseller',
    variants: [],
    materials: 'German silver alloy, oxidised antique finish',
    dimensions: 'Length: ~4.5cm, Width: ~2cm',
    care: 'Store in zip-lock bag. Do not expose to perfumes or moisture.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-02',
    name: 'Chandbali Floral Oxidised Studs',
    tagline: 'Crescent moon motif with delicate floral embossing',
    description: 'Inspired by traditional Bengali motifs, these crescent studs offer an understated vintage silhouette that elevates everyday ethnic styling.',
    price: 99,
    image: '/images/products/oxidised-earrings/oxidised-02.jpg',
    category: 'oxidised-earrings',
    variants: [],
    materials: 'Oxidised alloy, antique patina',
    dimensions: 'Length: ~3.8cm',
    care: 'Store away from direct moisture.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-03',
    name: 'Filigree Drop Oxidised Earrings',
    tagline: 'Airy filigree wirework in an antique silver finish',
    description: 'Delicate openwork filigree pattern that catches the light gently without adding weight. Versatile pairing for kurtas and sarees.',
    price: 99,
    image: '/images/products/oxidised-earrings/oxidised-03.jpg',
    category: 'oxidised-earrings',
    variants: [],
    materials: 'Oxidised brass alloy, surgical steel posts',
    dimensions: 'Length: ~4cm',
    care: 'Store in moisture-free pouch.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-04',
    name: 'Peacock Motif Oxidised Danglers',
    tagline: 'Graceful peacock carving with tiny ghungroo bells',
    description: 'A celebratory motif featuring the iconic mayur (peacock) design in deep antique oxidised polish. Embellished with subtle bead drops.',
    price: 99,
    image: '/images/products/oxidised-earrings/oxidised-04.jpg',
    category: 'oxidised-earrings',
    variants: [],
    materials: 'Silver alloy, oxidised finish',
    dimensions: 'Length: ~4.5cm',
    care: 'Keep in dry airtight container.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-05',
    name: 'Heritage Jhumki Oxidised Danglers',
    tagline: 'Two-tier carved dome jhumka with antique finish',
    description: 'Grand yet comfortable, these two-tier jhumkis boast heritage carving on the upper stud and a flared lower bell.',
    price: 109,
    image: '/images/products/oxidised-earrings/oxidised-05.jpg',
    category: 'oxidised-earrings',
    badge: 'New',
    variants: [],
    materials: 'High-grade oxidised metal',
    dimensions: 'Length: ~5cm, Width: ~2.2cm',
    care: 'Store dry in an airtight zip bag.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-06',
    name: 'Vintage Carved Oxidised Earrings',
    tagline: 'Intricate temple-inspired carving with antique luster',
    description: 'Rich temple-style architectural patterns condensed into a wearable, charming drop earring. Antiqued to perfection.',
    price: 109,
    image: '/images/products/oxidised-earrings/oxidised-06.jpg',
    category: 'oxidised-earrings',
    variants: [],
    materials: 'Oxidised brass alloy',
    dimensions: 'Length: ~4.8cm',
    care: 'Clean with dry cotton swab when required.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-07',
    name: 'Ornate Tribal Oxidised Earrings',
    tagline: 'Geometric and tribal lines with miniature bell drops',
    description: 'Inspired by eastern Indian tribal metalcraft, featuring geometric accents that give an artistic, bohemian flair.',
    price: 109,
    image: '/images/products/oxidised-earrings/oxidised-07.jpg',
    category: 'oxidised-earrings',
    variants: [],
    materials: 'Oxidised alloy with dark patina',
    dimensions: 'Length: ~5.2cm',
    care: 'Store in a cool dry space.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
  {
    id: 'oxidised-08',
    name: 'Statement Festive Oxidised Earrings',
    tagline: 'Grand chandelier oxidised earrings for celebratory evenings',
    description: 'The crowning piece of the oxidised collection. Elaborate multi-tiered design with graceful motion and captivating detail.',
    price: 129,
    image: '/images/products/oxidised-earrings/oxidised-08.jpg',
    category: 'oxidised-earrings',
    badge: 'Bestseller',
    variants: [],
    materials: 'Oxidised alloy with protective coat',
    dimensions: 'Length: ~6cm, Width: ~3cm',
    care: 'Store in soft velvet pouch or zip bag.',
    leadTime: 'Ready to ship. Dispatched in 1–2 working days.',
    isActive: true,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id && p.isActive)
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category && p.isActive)
}
